config/routes.rb
Rails.application.routes.draw do
  resources :books do
    member do
      get :delete
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  scope :sorted, lambda { order("id ASC") }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.sorted
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      flash[:notice] = "Book '#{@book.title}' created successfully."
      redirect_to(books_path)
    else
      render('new')
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])

    if @book.update_attributes(book_params)
      flash[:notice] = "Book '#{@book.title}' updated successfully."
      redirect_to(book_path(@book))
    else
      render('edit')
    end
  end

  def delete
    @book = Book.find(params[:id])
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    flash[:notice] = "Book '#{@book.title}' deleted successfully."
    redirect_to(books_path)
  end


  private

  def book_params
    params.require(:book).permit(:id, :title, :author, :genre, :price, :published_date, :created_at, :updated_at)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/delete.html.erb
<%= link_to("Home", books_path, :class => 'back-link') %>

<div class="books delete">
  <h2>Delete Book</h2>

  <%= form_for(@book, :method => 'delete') do |f| %>
    <p>
      Are you sure you want to delete this book:
      <var class="reference-name"><%= f.object.title %></var>
    </p>

    <div class="form-buttons">
      <%= f.submit("Delete") %>
    </div>
  <% end %>
</div>

app/views/books/edit.html.erb
<%= link_to("Home", books_path, :class => 'back-link') %>

<div class="book edit">
  <h2>Update Book</h2>

  <%= form_for(@book) do |f| %>

    <table summary="Book form fields">
      <tr>
        <th>Title</th>
        <td><%= f.text_field(:title, { :required => true }) %></td>
      </tr>
      <tr>
        <th>Author</th>
        <td><%= f.text_field(:author, { :required => true }) %></td>
      </tr>
      <tr>
        <th>Genre</th>
        <td><%= f.select(:genre, ['Young Adult', 'Fantasy', 'Children\'s', 'Literary Fiction', 'Science Fiction', 'Thrillers/Suspense', 'Middle Grade', 'Romance', 'Picture Book', 'Historical', 'Other'], {}, { :class => 'my_style_class', :required => true }) %></td>
      </tr>
      <tr>
        <th>Price</th>
        <td><%= f.text_field(:price, { :required => true }) %></td>
      </tr>
      <tr>
        <th>Published Date</th>
        <td><%= f.date_field(:published_date, { :value => @book.published_date, :required => true }) %></td>
      </tr>
    </table>

    <div class="form-buttons">
      <%= f.submit("Update Book") %>
    </div>

  <% end %>
</div>

app/views/books/index.html.erb
<% if !flash[:notice].blank? %>
  <div class="notice">
    <%= flash[:notice] %>
  </div>
<% end %>

<div class="books index">
  <h2>Book Collection</h2>

  <%= link_to("Add Book", new_book_path, :class => 'action new') %>

  <table class="listing" summary="Book list">
    <tr class="header">
      <th>id</th>
      <th>Title</th>
      <th>Author</th>
      <th>Actions</th>
    </tr>
    <% @books.each do |book| %>
    <tr>
      <td><%= book.id %></td>
      <td><%= book.title %></td>
      <td><%= book.author %></td>
      <td class="actions">
        <%= link_to("Show", book_path(book), :class => 'action show') %>
        <%= link_to("Update", edit_book_path(book), :class => 'action edit') %>
        <%= link_to("Delete", delete_book_path(book), :class => 'action delete') %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/books/new.html.erb
<%= link_to("Home", books_path, :class => 'back-link') %>

<div class="books new">
  <h2>Create Book</h2>

  <%= form_for(@book) do |f| %>

    <table summary="Book form fields">
      <tr>
        <th>Title</th>
        <td><%= f.text_field(:title, { :required => true }) %></td>
      </tr>
      <tr>
        <th>Author</th>
        <td><%= f.text_field(:author, { :required => true }) %></td>
      </tr>
      <tr>
        <th>Genre</th>
        <td><%= f.select(:genre, ['Young Adult', 'Fantasy', 'Children\'s', 'Literary Fiction', 'Science Fiction', 'Thrillers/Suspense', 'Middle Grade', 'Romance', 'Picture Book', 'Historical', 'Other'], {}, { :class => 'my_style_class', :required => true }) %></td>
      </tr>
      <tr>
        <th>Price</th>
        <td><%= f.text_field(:price, { :required => true }) %></td>
      </tr>
      <tr>
        <th>Published Date</th>
        <td><%= f.date_field(:published_date, { :required => true }) %></td>
      </tr>
    </table>

    <div class="form-buttons">
      <%= f.submit("Create Book") %>
    </div>

  <% end %>
</div>

app/views/books/show.html.erb
<% if !flash[:notice].blank? %>
  <div class="notice">
    <%= flash[:notice] %>
  </div>
<% end %>

<%= link_to("Home", books_path, :class => 'back-link') %>

<div class="books show">
  <h2>Show Book</h2>

  <table summary="Book detail view">
    <tr>
      <th>id</th>
      <td><%= @book.id %></td>
    </tr>
    <tr>
      <th>Title</th>
      <td><%= @book.title %></td>
    </tr>
    <tr>
      <th>Author</th>
      <td><%= @book.author %></td>
    </tr>
    <tr>
      <th>Genre</th>
      <td><%= @book.genre %></td>
    </tr>
    <tr>
      <th>Price</th>
      <td><%= @book.price %></td>
    </tr>
    <tr>
      <th>Published Date</th>
      <td><%= @book.published_date %></td>
    </tr>
    <tr>
      <th>Time Created</th>
      <td><%= @book.created_at %></td>
    </tr>
    <tr>
      <th>Last Updated</th>
      <td><%= @book.updated_at %></td>
    </tr>
  </table>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>